version: '3.3'

services:
  bdayrem:
    build:
      context: '.'
      dockerfile: Dockerfile
    ports:
      - 3200:3200
    container_name: bdayapp
    image: spygram/bdayimage:latest
    networks:
      - bday-net

networks:
  bday-net:
    driver: bridge
